
name: Date

on:
  issues:
    types:
      - opened
      - edited
      - closed
  pull_request:
    types:
      - ready_for_review
  gollum:
    types:
      - created
      - edited
      - deleted
  schedule:
    - cron: '0 0 1 * *'
  workflow_dispatch:

jobs:
  print_date:
    runs-on: ubuntu-latest
    steps:
      - name: hello_date
        run: echo "Hello, world! Today is $(date +%m)-$(date +%d)-$(date +%Y) $(date +%H):$(date +%M):$(date +%S)"
      
