name: latest_environments

on:
  workflow_dispatch:

jobs:
  ubuntu:
    runs-on: ubuntu-latest
    steps:
      - name: ubuntu_version
        run: lsb_release -v
  windows:
    runs-on: windows-latest
    steps:
      - name: windows_version
        run: Get-ComputerInfo -Property "*version"
  macos:
    runs-on: macos-latest
    steps:
      - name: macos_version
        run: sw_vers -productVersion
