name: latest_environments

on:
  workflow_dispatch:

jobs:
  ubuntu:
    runs-on: ubuntu-latest
    steps:
      run:
  windows:
    runs-on: windows-latest
    steps:
      run:
  macos:
    runs-on: macos-latest
    steps:
      run: sw_vers -productVersion
